// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtcsnryUJIdbeJGx7WaBu_gnIqITwMmF0',
    appId: '1:459276707825:web:f2f354f226190a6dba8650',
    messagingSenderId: '459276707825',
    projectId: 'first-project-13d5e',
    authDomain: 'first-project-13d5e.firebaseapp.com',
    storageBucket: 'first-project-13d5e.appspot.com',
    measurementId: 'G-FSXLCXG9EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDasGta0rfOjzwMFnTVELWprU2SAnuC4rE',
    appId: '1:459276707825:android:65bae9f6343b00efba8650',
    messagingSenderId: '459276707825',
    projectId: 'first-project-13d5e',
    storageBucket: 'first-project-13d5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGW_IYE4DWdL2dATRgwsABQdMj1qS-5M',
    appId: '1:459276707825:ios:3218eb5fea391ea6ba8650',
    messagingSenderId: '459276707825',
    projectId: 'first-project-13d5e',
    storageBucket: 'first-project-13d5e.appspot.com',
    iosClientId: '459276707825-1ji7ldk53tkgds1nln3og6rdi2g02bsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.southsupply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHGW_IYE4DWdL2dATRgwsABQdMj1qS-5M',
    appId: '1:459276707825:ios:3218eb5fea391ea6ba8650',
    messagingSenderId: '459276707825',
    projectId: 'first-project-13d5e',
    storageBucket: 'first-project-13d5e.appspot.com',
    iosClientId: '459276707825-1ji7ldk53tkgds1nln3og6rdi2g02bsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.southsupply',
  );
}
